# -*- coding: utf-8 -*-
"""clickbait_optimized_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gnVLuHZT5lJfDsotqxTPCuVeJ4ZDINsm

## STEP 0 — Install & Import
"""

# Only install what's missing in Colab — sklearn/pandas/matplotlib already available
!pip install -q transformers torch --upgrade
print('Done')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re, time, warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection         import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing           import StandardScaler
from sklearn.linear_model            import LogisticRegression
from sklearn.ensemble                import RandomForestClassifier
from sklearn.svm                     import LinearSVC
from sklearn.metrics                 import (classification_report, confusion_matrix,
                                             accuracy_score, f1_score,
                                             precision_score, recall_score)
from scipy.sparse import hstack, csr_matrix

SEED = 42
np.random.seed(SEED)
print(' All imports done!')

# ── Upload bangla_clickbait_processed__1_.csv via Colab Files panel ─────────
# This file has 10,000 rows and ALL features already computed:
# title, title_clean, viewCount, likeCount, commentCount, dislikeCount,
# feat_char_len, feat_word_count, feat_exclaim, feat_question,
# feat_has_number, feat_caps_ratio, human_labeled, label

FILE = 'bangla_clickbait_processed__1_.csv'

df = pd.read_csv(FILE, encoding='utf-8-sig')

# Fix the 1 null in title_clean
df['title_clean'] = df['title_clean'].fillna('')

print(f' Loaded: {df.shape[0]} rows × {df.shape[1]} columns')
print(f'\nLabel distribution:')
print(df['human_labeled'].value_counts())
print(f'\nClickbait ratio : {(df["label"]==1).mean():.2%}')
print(f'Null values     : {df.isna().sum().sum()} (should be 0)')
df.head(2)

"""### EDA — Exploratory Data Analysis"""

print(' Title statistics by label:')
print(df.groupby('human_labeled')[['feat_char_len','feat_word_count',
                                    'feat_exclaim','feat_question']].mean().round(2))
print()
print(' Engagement median by label:')
print(df.groupby('human_labeled')[['viewCount','likeCount',
                                    'commentCount','dislikeCount']].median().round(0))

# ── Figure 1: Class Distribution + Engagement ─────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
fig.suptitle('BaitBuster-Bangla — Human-Labeled 10,000 Samples',
             fontsize=13, fontweight='bold')

vc = df['human_labeled'].value_counts()
axes[0].pie(vc.values, labels=vc.index, autopct='%1.1f%%',
            colors=['#ef5350','#42a5f5'], startangle=90,
            wedgeprops={'edgecolor':'white','linewidth':2},
            textprops={'fontsize':12})
axes[0].set_title('Class Distribution', fontweight='bold')

eng = df.groupby('human_labeled')[['viewCount','likeCount',
                                    'commentCount','dislikeCount']].median()
eng.T.plot(kind='bar', ax=axes[1], color=['#ef5350','#42a5f5'], alpha=0.85, width=0.6)
axes[1].set_title('Median Engagement by Label', fontweight='bold')
axes[1].set_xticklabels(['Views','Likes','Comments','Dislikes'], rotation=0)
axes[1].set_ylabel('Median Count')
axes[1].legend(title='Label')
axes[1].grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('fig1_eda.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: fig1_eda.png')

# ── Figure 2: Title Length Distribution ──────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
fig.suptitle('Title Length: Clickbait vs Not Clickbait', fontsize=13, fontweight='bold')

for label, color in [('Clickbait','#ef5350'), ('Not Clickbait','#42a5f5')]:
    sub = df[df['human_labeled'] == label]
    axes[0].hist(sub['feat_char_len'],  bins=40, alpha=0.65, label=label, color=color)
    axes[1].hist(sub['feat_word_count'], bins=30, alpha=0.65, label=label, color=color)

for ax, xlabel, title in zip(axes,
    ['Number of Characters', 'Number of Words'],
    ['Character Length', 'Word Count']):
    ax.set_title(title, fontweight='bold')
    ax.set_xlabel(xlabel)
    ax.set_ylabel('Frequency')
    ax.legend()
    ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('fig2_title_length.png', dpi=150, bbox_inches='tight')
plt.show()
print(' Saved: fig2_title_length.png')
print(f"\nAvg char length — Clickbait: {df[df['human_labeled']=='Clickbait']['feat_char_len'].mean():.1f}"
      f" | Not Clickbait: {df[df['human_labeled']=='Not Clickbait']['feat_char_len'].mean():.1f}")
print(f"Avg word count  — Clickbait: {df[df['human_labeled']=='Clickbait']['feat_word_count'].mean():.1f}"
      f" | Not Clickbait: {df[df['human_labeled']=='Not Clickbait']['feat_word_count'].mean():.1f}")

# ── Train / Test Split 80:20 stratified ──────────────────────────────────────
y = df['label'].values

train_df, test_df = train_test_split(
    df, test_size=0.2, random_state=SEED, stratify=y
)
train_df = train_df.reset_index(drop=True)
test_df  = test_df.reset_index(drop=True)

y_train = train_df['label'].values
y_test  = test_df['label'].values

print(f'Train : {len(train_df):,} rows | Test: {len(test_df):,} rows')
print(f'Train — Clickbait: {(y_train==1).sum():,} | Not: {(y_train==0).sum():,}')
print(f'Test  — Clickbait: {(y_test==1).sum():,}  | Not: {(y_test==0).sum():,}')

# ── F1: TF-IDF (10K features, unigram+bigram) ────────────────────────────────
tfidf = TfidfVectorizer(max_features=10000, ngram_range=(1,2), min_df=2, sublinear_tf=True)
X_f1_train = tfidf.fit_transform(train_df['title_clean'])
X_f1_test  = tfidf.transform(test_df['title_clean'])
print(f'\nF1 TF-IDF  : {X_f1_train.shape}')

# ── F2: Engagement + Linguistic (log-normalized) ─────────────────────────────
META = ['viewCount','likeCount','commentCount','dislikeCount',
        'feat_char_len','feat_word_count','feat_exclaim',
        'feat_question','feat_has_number','feat_caps_ratio']

def build_meta(d):
    m = d[META].copy().fillna(0)
    for c in ['viewCount','likeCount','commentCount','dislikeCount']:
        m[c] = np.log1p(m[c])          # log-normalize skewed counts
    return m.values

scaler = StandardScaler()
X_f2_train = scaler.fit_transform(build_meta(train_df))
X_f2_test  = scaler.transform(build_meta(test_df))
print(f'F2 Metadata: {X_f2_train.shape}')

# ── F3: Combined ──────────────────────────────────────────────────────────────
X_f3_train = hstack([X_f1_train, csr_matrix(X_f2_train)])
X_f3_test  = hstack([X_f1_test,  csr_matrix(X_f2_test)])
print(f'F3 Combined: {X_f3_train.shape}')

FEATURE_SETS = {
    'TF-IDF Only':       (X_f1_train, X_f1_test),
    'Metadata Only':     (csr_matrix(X_f2_train), csr_matrix(X_f2_test)),
    'TF-IDF + Metadata': (X_f3_train, X_f3_test)
}
print('\n All feature sets ready!')

"""---
## STEP 3 — Train ML Models (LR · RF · SVM × 3 feature sets = 9 experiments)
"""

def get_scores(y_true, y_pred, model_name, fs_name):
    return {
        'Model':     model_name,
        'Features':  fs_name,
        'Accuracy':  round(accuracy_score(y_true, y_pred)*100, 2),
        'Precision': round(precision_score(y_true, y_pred, average='weighted', zero_division=0)*100, 2),
        'Recall':    round(recall_score(y_true, y_pred, average='weighted', zero_division=0)*100, 2),
        'F1-Score':  round(f1_score(y_true, y_pred, average='weighted', zero_division=0)*100, 2)
    }

MODELS = {
    'Logistic Regression': LogisticRegression(C=1.0, max_iter=1000, random_state=SEED),
    'Random Forest':       RandomForestClassifier(n_estimators=100, n_jobs=-1,
                                                   random_state=SEED),   # 100 trees = faster
    'SVM':                 LinearSVC(C=1.0, max_iter=2000, random_state=SEED)
}

all_results    = []
trained_models = {}        # store best (combined) model per classifier
bert_row       = None      # filled later if BanglaBERT runs

for model_name, model in MODELS.items():
    print(f'\n━━━ {model_name} ━━━')
    for fs_name, (X_tr, X_te) in FEATURE_SETS.items():
        t0     = time.time()
        model.fit(X_tr, y_train)
        y_pred = model.predict(X_te)
        row    = get_scores(y_test, y_pred, model_name, fs_name)
        row['Time'] = f'{time.time()-t0:.1f}s'
        all_results.append(row)
        print(f'  {fs_name:<22}  Acc={row["Accuracy"]:5.2f}%  F1={row["F1-Score"]:5.2f}%  ({row["Time"]})')
        if fs_name == 'TF-IDF + Metadata':
            trained_models[model_name] = (model, y_pred.copy())

results_df = pd.DataFrame(all_results)
print('\n All ML models trained!')

# ── Detailed report for best feature set ─────────────────────────────────────
print('='*60)
print('DETAILED CLASSIFICATION REPORTS — TF-IDF + Metadata')
print('='*60)
for name, (_, preds) in trained_models.items():
    print(f'\n[{name}]')
    print(classification_report(y_test, preds,
                                target_names=['Not Clickbait','Clickbait']))

"""---
## STEP 4  BanglaBERT Fine-tuning

> **GPU required!** Runtime Change runtime type **T4 GPU** before running this step.
> Expected time: ~15 min on free Colab T4.
>
> Set `RUN_BERT = False` if you want to skip and use ML results only.
"""

!pip uninstall -y torch torchvision torchaudio transformers

!pip install -q torch torchvision torchaudio
!pip install -q transformers accelerate sentencepiece

!pip install -q transformers==4.41.2 sentencepiece accelerate

RUN_BERT = True

if RUN_BERT:

    import torch
    from torch.utils.data import Dataset, DataLoader

    from transformers import (
        AutoTokenizer,
        AutoModelForSequenceClassification,
        get_linear_schedule_with_warmup
    )

    from torch.optim import AdamW

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    print("Device:", device)

    MODEL_NAME = "csebuetnlp/banglabert"

    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=2
    )

    model.to(device)

    print("BanglaBERT loaded successfully!")

else:
    print("BERT skipped")

if RUN_BERT:
    class ClickbaitDataset(Dataset):
        def __init__(self, texts, labels, tok, max_len=128):
            self.texts, self.labels = list(texts), list(labels)
            self.tok, self.max_len  = tok, max_len
        def __len__(self): return len(self.texts)
        def __getitem__(self, i):
            enc = self.tok(self.texts[i], max_length=self.max_len,
                           padding='max_length', truncation=True, return_tensors='pt')
            return {'input_ids':      enc['input_ids'].squeeze(),
                    'attention_mask': enc['attention_mask'].squeeze(),
                    'label':          torch.tensor(self.labels[i], dtype=torch.long)}

    # ── Use full 8000 train / 2000 test rows — NOT a sample ──────────────────
    BATCH  = 32      # safe for T4 15GB
    MAXLEN = 128

    tr_loader = DataLoader(
        ClickbaitDataset(train_df['title'].tolist(), y_train.tolist(), tokenizer, MAXLEN),
        batch_size=BATCH, shuffle=True, num_workers=2, pin_memory=True
    )
    te_loader = DataLoader(
        ClickbaitDataset(test_df['title'].tolist(), y_test.tolist(), tokenizer, MAXLEN),
        batch_size=64, shuffle=False, num_workers=2, pin_memory=True  # bigger batch for eval
    )
    print(f'Train batches: {len(tr_loader)} | Test batches: {len(te_loader)}')
    print(f'Train samples: {len(train_df):,} | Test samples: {len(test_df):,}')
else:
    print('Skipped.')

if RUN_BERT:
    EPOCHS = 3
    LR     = 2e-5

    bert = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)
    bert = bert.to(device)

    # Use torch.compile if available (PyTorch 2.0+ — speeds up ~10-20%)
    try:
        bert = torch.compile(bert)
        print('torch.compile enabled')
    except Exception:
        pass

    optimizer   = AdamW(bert.parameters(), lr=LR, eps=1e-8, weight_decay=0.01)
    total_steps = len(tr_loader) * EPOCHS
    scheduler   = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps   = int(total_steps * 0.06),   # 6% warmup
        num_training_steps = total_steps
    )
    scaler_amp  = torch.cuda.amp.GradScaler()           # mixed precision — ~1.5x faster

    print(f' BanglaBERT training — {EPOCHS} epochs | LR={LR} | Batch={BATCH}')
    print(f'   Total steps: {total_steps} | Warmup: {int(total_steps*0.06)}\n')

    for ep in range(EPOCHS):
        bert.train()
        ep_loss, correct, total = 0.0, 0, 0
        for i, batch in enumerate(tr_loader):
            ids  = batch['input_ids'].to(device)
            mask = batch['attention_mask'].to(device)
            lbls = batch['label'].to(device)
            optimizer.zero_grad()

            with torch.cuda.amp.autocast():              # mixed precision forward
                out  = bert(input_ids=ids, attention_mask=mask, labels=lbls)

            scaler_amp.scale(out.loss).backward()
            scaler_amp.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(bert.parameters(), 1.0)
            scaler_amp.step(optimizer)
            scaler_amp.update()
            scheduler.step()

            ep_loss += out.loss.item()
            correct += (torch.argmax(out.logits,1) == lbls).sum().item()
            total   += lbls.size(0)

            if (i+1) % 50 == 0:
                print(f'  Ep {ep+1}/{EPOCHS} | Step {i+1}/{len(tr_loader)} '
                      f'| Loss: {ep_loss/(i+1):.4f} | Acc: {correct/total:.4f}')

        print(f'   Epoch {ep+1} — Avg Loss: {ep_loss/len(tr_loader):.4f} '
              f'| Train Acc: {correct/total:.4f}\n')

    print(' BanglaBERT training complete!')
else:
    print('Skipped.')

if RUN_BERT:
    bert.eval()
    bert_preds, bert_true = [], []

    with torch.no_grad():
        for batch in te_loader:
            with torch.cuda.amp.autocast():
                out = bert(input_ids=batch['input_ids'].to(device),
                           attention_mask=batch['attention_mask'].to(device))
            bert_preds.extend(torch.argmax(out.logits,1).cpu().numpy())
            bert_true.extend(batch['label'].numpy())

    bert_preds = np.array(bert_preds)
    bert_true  = np.array(bert_true)

    bert_row = get_scores(bert_true, bert_preds, 'BanglaBERT', 'Transformer')
    all_results.append(bert_row)

    print(' BanglaBERT Results:')
    for k, v in bert_row.items(): print(f'   {k}: {v}')
    print()
    print(classification_report(bert_true, bert_preds,
                                target_names=['Not Clickbait','Clickbait']))
else:
    bert_preds = bert_true = None
    print('BanglaBERT skipped.')

"""---
## STEP 5 — Paper Figures
"""

# ── Figure 3: F1-Score Heatmap ────────────────────────────────────────────────
heat = results_df.pivot_table(index='Model', columns='Features', values='F1-Score')

plt.figure(figsize=(9, 4))
sns.heatmap(heat, annot=True, fmt='.2f', cmap='YlOrRd',
            linewidths=0.5, linecolor='white',
            cbar_kws={'label': 'F1-Score (%)'},
            annot_kws={'size': 11, 'weight': 'bold'})
plt.title('F1-Score Heatmap: Model vs Feature Set', fontsize=13, fontweight='bold')
plt.xlabel('Feature Set', fontsize=11)
plt.ylabel('Model', fontsize=11)
plt.tight_layout()
plt.savefig('fig3_f1_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()
print(' Saved: fig3_f1_heatmap.png')

# ── Figure 4: Final Model Comparison Bar Chart ────────────────────────────────
best_ml = results_df[results_df['Features']=='TF-IDF + Metadata'].copy()
final   = pd.concat([best_ml, pd.DataFrame([bert_row])],
                    ignore_index=True) if bert_row else best_ml.copy()

metrics = ['Accuracy','Precision','Recall','F1-Score']
x       = np.arange(len(final))
width   = 0.2
clrs    = ['#1565C0','#2E7D32','#E65100','#B71C1C']

fig, ax = plt.subplots(figsize=(12, 6))
for i, (m, c) in enumerate(zip(metrics, clrs)):
    vals = final[m].values.astype(float)
    bars = ax.bar(x + i*width, vals, width, label=m, color=c, alpha=0.87)
    for bar, v in zip(bars, vals):
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.2,
                f'{v:.1f}', ha='center', fontsize=8, fontweight='bold')

ax.set_xticks(x + width*1.5)
ax.set_xticklabels(final['Model'], fontsize=10)
ax.set_ylim(50, 100)
ax.set_ylabel('Score (%)', fontsize=11)
ax.set_title('Model Performance Comparison — Bangla YouTube Clickbait Detection',
             fontsize=13, fontweight='bold')
ax.legend(fontsize=10)
ax.grid(axis='y', alpha=0.3)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig('fig4_model_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print(' Saved: fig4_model_comparison.png')

# ── Figure 5: Confusion Matrices ─────────────────────────────────────────────
cm_data = {name: (y_test, preds) for name, (_, preds) in trained_models.items()}
if bert_row and bert_preds is not None:
    cm_data['BanglaBERT'] = (bert_true, bert_preds)

n   = len(cm_data)
fig, axes = plt.subplots(1, n, figsize=(5*n, 4))
fig.suptitle('Confusion Matrices — All Models (Best Feature Set)',
             fontsize=13, fontweight='bold')
if n == 1: axes = [axes]

for ax, (name, (true, pred)) in zip(axes, cm_data.items()):
    cm = confusion_matrix(true, pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=['Not CB','CB'], yticklabels=['Not CB','CB'], cbar=False)
    ax.set_title(name, fontsize=10, fontweight='bold')
    ax.set_xlabel('Predicted', fontsize=9)
    ax.set_ylabel('Actual', fontsize=9)

plt.tight_layout()
plt.savefig('fig5_confusion_matrices.png', dpi=150, bbox_inches='tight')
plt.show()
print(' Saved: fig5_confusion_matrices.png')

# ── Figure 6: Top TF-IDF Keywords (Logistic Regression) ─────────────────────
lr_model  = trained_models['Logistic Regression'][0]
fnames    = tfidf.get_feature_names_out()
coef_text = lr_model.coef_[0][:len(fnames)]    # text-feature coefficients only
N         = 15

top_cb  = np.argsort(coef_text)[-N:][::-1]
top_ncb = np.argsort(coef_text)[:N]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle('Top Discriminative Keywords — Logistic Regression Coefficients',
             fontsize=13, fontweight='bold')

ax1.barh(range(N), coef_text[top_cb],            color='#ef5350', alpha=0.85)
ax1.set_yticks(range(N))
ax1.set_yticklabels([fnames[i] for i in top_cb],  fontsize=9)
ax1.set_title('Top Clickbait Indicators',     fontweight='bold')
ax1.set_xlabel('LR Coefficient')

ax2.barh(range(N), np.abs(coef_text[top_ncb]),    color='#42a5f5', alpha=0.85)
ax2.set_yticks(range(N))
ax2.set_yticklabels([fnames[i] for i in top_ncb], fontsize=9)
ax2.set_title('Top Not-Clickbait Indicators', fontweight='bold')
ax2.set_xlabel('|LR Coefficient|')

plt.tight_layout()
plt.savefig('fig6_keywords.png', dpi=150, bbox_inches='tight')
plt.show()
print(' Saved: fig6_keywords.png')

# ── Figure 7: BanglaBERT Training Curve ──────────────────────────────────────
epochs      = [1, 2, 3]
train_loss  = [0.1682, 0.0303, 0.0129]   # তোমার actual values
train_acc   = [95.53,  99.29,  99.71]    # তোমার actual values
test_acc_line = 98.70                     # final test accuracy

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle('BanglaBERT Training Curve', fontsize=13, fontweight='bold')

# Loss
ax1.plot(epochs, train_loss, 'o-', color='#B71C1C', linewidth=2.5,
         markersize=9, markerfacecolor='white', markeredgewidth=2.5)
for x, y in zip(epochs, train_loss):
    ax1.annotate(f'{y:.4f}', (x, y), textcoords='offset points',
                 xytext=(0, 12), ha='center', fontsize=10,
                 fontweight='bold', color='#B71C1C')
ax1.fill_between(epochs, train_loss, alpha=0.08, color='#B71C1C')
ax1.set_xlabel('Epoch'); ax1.set_ylabel('Loss')
ax1.set_title('Training Loss per Epoch', fontweight='bold')
ax1.set_xticks([1, 2, 3])

# Accuracy
ax2.plot(epochs, train_acc, 's-', color='#1565C0', linewidth=2.5,
         markersize=9, markerfacecolor='white', markeredgewidth=2.5,
         label='Train Accuracy')
ax2.axhline(test_acc_line, color='#2E7D32', linestyle='--',
            linewidth=2, label=f'Test Accuracy ({test_acc_line}%)')
for x, y in zip(epochs, train_acc):
    ax2.annotate(f'{y:.2f}%', (x, y), textcoords='offset points',
                 xytext=(0, 10), ha='center', fontsize=10,
                 fontweight='bold', color='#1565C0')
ax2.fill_between(epochs, train_acc, alpha=0.08, color='#1565C0')
ax2.set_xlabel('Epoch'); ax2.set_ylabel('Accuracy (%)')
ax2.set_title('Train vs Test Accuracy', fontweight='bold')
ax2.set_xticks([1, 2, 3])
ax2.set_ylim(93, 101)
ax2.legend(fontsize=10)

plt.tight_layout()
plt.savefig('fig7_bert_training_curve.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ Saved: fig7_bert_training_curve.png')

"""---
## STEP 6 — Final Results Table (Copy-Paste to Paper)
"""

print('='*72)
print('TABLE II. PERFORMANCE COMPARISON OF CLASSIFICATION MODELS')
print('='*72)
print(f'{"Model":<22} {"Feature Set":<22} {"Acc%":>6} {"Prec%":>6} {"Rec%":>6} {"F1%":>6}')
print('-'*72)

for _, r in results_df.sort_values(['Model','Features']).iterrows():
    print(f'{r["Model"]:<22} {r["Features"]:<22} '
          f'{r["Accuracy"]:>6} {r["Precision"]:>6} '
          f'{r["Recall"]:>6} {r["F1-Score"]:>6}')

if bert_row:
    print(f'{"BanglaBERT":<22} {"Transformer":<22} '
          f'{bert_row["Accuracy"]:>6} {bert_row["Precision"]:>6} '
          f'{bert_row["Recall"]:>6} {bert_row["F1-Score"]:>6}')
print('='*72)

# Best model overall
all_f1    = [(f"{r['Model']} ({r['Features']})", r['F1-Score']) for _, r in results_df.iterrows()]
if bert_row: all_f1.append(('BanglaBERT (Transformer)', bert_row['F1-Score']))
best_name, best_f1 = max(all_f1, key=lambda x: x[1])
print(f'\n Best overall: {best_name}  |  F1 = {best_f1}%')

results_df.to_csv('results_final.csv', index=False)
print('\n Paper figures generated:')
for f in ['fig1_eda.png','fig2_title_length.png','fig3_f1_heatmap.png',
          'fig4_model_comparison.png','fig5_confusion_matrices.png','fig6_keywords.png']:
    print(f'   {f}')